BEGIN IMMEDIATE;
CREATE TABLE session_heads(session_id TEXT PRIMARY KEY REFERENCES sessions(id),lifetime TEXT NOT NULL UNIQUE,deleted INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 0,projection_generation INTEGER NOT NULL DEFAULT 0,run_generation INTEGER NOT NULL DEFAULT 0,legacy_imported INTEGER NOT NULL DEFAULT 0,updated_at_ms INTEGER NOT NULL);
INSERT INTO session_heads(session_id,lifetime,updated_at_ms) SELECT id,lower(hex(randomblob(16))),created_at_ms FROM sessions;
CREATE TABLE lifecycle_receipts(operation_id TEXT PRIMARY KEY,command_json TEXT NOT NULL,result_json TEXT NOT NULL);
CREATE TABLE runtime_settings(name TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE session_tombstones(lifetime TEXT PRIMARY KEY,session_id TEXT NOT NULL,deleted_at_ms INTEGER NOT NULL);
CREATE TABLE transcript_batches(lifetime TEXT NOT NULL,operation_id TEXT NOT NULL,run_id TEXT REFERENCES runs(id),start_seq INTEGER NOT NULL,end_seq INTEGER NOT NULL,messages_json TEXT NOT NULL,digest TEXT NOT NULL,UNIQUE(lifetime,operation_id));
CREATE INDEX transcript_source ON transcript_batches(lifetime,start_seq);
ALTER TABLE runs ADD COLUMN lifetime TEXT NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN generation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN request_id_wire_json TEXT;
UPDATE runs SET lifetime=(SELECT lifetime FROM session_heads WHERE session_id=runs.session_id),generation=rowid,request_id_wire_json=request_id_json;
UPDATE runs SET request_id_json=json_array(lifetime,json(request_id_wire_json));
UPDATE session_heads SET run_generation=COALESCE((SELECT MAX(generation) FROM runs WHERE session_id=session_heads.session_id),0);
CREATE TRIGGER session_incarnation AFTER INSERT ON sessions BEGIN
  INSERT INTO session_heads(session_id,lifetime,updated_at_ms) VALUES (NEW.id,lower(hex(randomblob(16))),NEW.created_at_ms);
END;
CREATE TRIGGER run_incarnation AFTER INSERT ON runs BEGIN
  SELECT CASE WHEN (SELECT run_generation FROM session_heads WHERE session_id=NEW.session_id)>=9223372036854775807 THEN RAISE(ABORT,'run generation exhausted') END;
  SELECT CASE WHEN (SELECT deleted FROM session_heads WHERE session_id=NEW.session_id)=1 THEN RAISE(ABORT,'deleted session') END;
  UPDATE session_heads SET run_generation=run_generation+1 WHERE session_id=NEW.session_id;
  UPDATE runs SET lifetime=(SELECT lifetime FROM session_heads WHERE session_id=NEW.session_id),generation=(SELECT run_generation FROM session_heads WHERE session_id=NEW.session_id),request_id_wire_json=NEW.request_id_json,request_id_json=json_array((SELECT lifetime FROM session_heads WHERE session_id=NEW.session_id),json(NEW.request_id_json)) WHERE rowid=NEW.rowid;
END;
CREATE TRIGGER run_lifetime_fence BEFORE UPDATE ON runs WHEN OLD.lifetime<>'' AND NOT EXISTS(SELECT 1 FROM session_heads h WHERE h.session_id=OLD.session_id AND h.lifetime=OLD.lifetime AND h.deleted=0) BEGIN SELECT RAISE(ABORT,'stale run lifetime'); END;
ALTER TABLE interactions ADD COLUMN lifetime TEXT NOT NULL DEFAULT '';
ALTER TABLE interactions ADD COLUMN generation INTEGER NOT NULL DEFAULT 0;
UPDATE interactions SET lifetime=(SELECT lifetime FROM runs WHERE id=interactions.run_id),generation=(SELECT generation FROM runs WHERE id=interactions.run_id);
ALTER TABLE tool_executions ADD COLUMN lifetime TEXT NOT NULL DEFAULT '';
ALTER TABLE tool_executions ADD COLUMN generation INTEGER NOT NULL DEFAULT 0;
UPDATE tool_executions SET lifetime=(SELECT lifetime FROM runs WHERE id=tool_executions.run_id),generation=(SELECT generation FROM runs WHERE id=tool_executions.run_id);
ALTER TABLE delegations ADD COLUMN parent_lifetime TEXT NOT NULL DEFAULT '';
ALTER TABLE delegations ADD COLUMN child_lifetime TEXT NOT NULL DEFAULT '';
UPDATE delegations SET parent_lifetime=(SELECT lifetime FROM runs WHERE id=parent_run_id),child_lifetime=(SELECT lifetime FROM runs WHERE id=child_run_id);
CREATE TRIGGER delegation_incarnation AFTER INSERT ON delegations BEGIN UPDATE delegations SET parent_lifetime=(SELECT lifetime FROM runs WHERE id=NEW.parent_run_id),child_lifetime=(SELECT lifetime FROM runs WHERE id=NEW.child_run_id) WHERE id=NEW.id; END;
CREATE TRIGGER interaction_incarnation AFTER INSERT ON interactions BEGIN UPDATE interactions SET lifetime=(SELECT lifetime FROM runs WHERE id=NEW.run_id),generation=(SELECT generation FROM runs WHERE id=NEW.run_id) WHERE id=NEW.id; END;
CREATE TRIGGER tool_incarnation AFTER INSERT ON tool_executions BEGIN UPDATE tool_executions SET lifetime=(SELECT lifetime FROM runs WHERE id=NEW.run_id),generation=(SELECT generation FROM runs WHERE id=NEW.run_id) WHERE id=NEW.id; END;
CREATE TRIGGER events_INSERT_owner BEFORE INSERT ON events WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER events_UPDATE_owner BEFORE UPDATE ON events WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER interactions_INSERT_owner BEFORE INSERT ON interactions WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER interactions_UPDATE_owner BEFORE UPDATE ON interactions WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER tool_executions_INSERT_owner BEFORE INSERT ON tool_executions WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER tool_executions_UPDATE_owner BEFORE UPDATE ON tool_executions WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER provider_attempts_INSERT_owner BEFORE INSERT ON provider_attempts WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER provider_attempts_UPDATE_owner BEFORE UPDATE ON provider_attempts WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER queued_messages_INSERT_owner BEFORE INSERT ON queued_messages WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER queued_messages_UPDATE_owner BEFORE UPDATE ON queued_messages WHEN NEW.run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER delegations_INSERT_owner BEFORE INSERT ON delegations WHEN NEW.parent_run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.parent_run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
CREATE TRIGGER delegations_UPDATE_owner BEFORE UPDATE ON delegations WHEN NEW.parent_run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM runs r JOIN session_heads h ON h.session_id=r.session_id AND h.lifetime=r.lifetime AND h.deleted=0 WHERE r.id=NEW.parent_run_id) BEGIN SELECT RAISE(ABORT,'stale fact owner'); END;
INSERT INTO schema_migrations VALUES(6,CAST(strftime('%s','now') AS INTEGER)*1000);
COMMIT;
